function(eps_set_install_paths)
if(WIN32)
    file(TO_CMAKE_PATH "$ENV{programfiles}" PROG_FILES)
endif()

if(APPLE)
    set(EPS_PLUGIN_INSTALL_PREFIX "$ENV{HOME}/Library/Audio/Plug-Ins/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
    set(EPS_EXTENSION_INSTALL_PREFIX "$ENV{HOME}/Library/Application Support/REAPER/" CACHE STRING "Extension path prefix, prepended onto extension install directory")
endif()
if(WIN32)
    set(EPS_PLUGIN_INSTALL_PREFIX "${PROG_FILES}/Common Files/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
    set(EPS_EXTENSION_INSTALL_PREFIX "${PROG_FILES}/REAPER (x64)/" CACHE STRING "Extension path prefix, prepended onto extension install directory")
endif()
endfunction()
