function(eps_set_install_paths)
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    if(WIN32)
        file(TO_CMAKE_PATH "$ENV{programfiles}" PROG_FILES)
        file(TO_CMAKE_PATH "$ENV{appdata}" APPDATA)
    endif()

    if(APPLE)
        set(EPS_PLUGIN_INSTALL_PREFIX "$ENV{HOME}/Library/Audio/Plug-Ins/VST3/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
        set(EPS_EXTENSION_INSTALL_PREFIX "$ENV{HOME}/Library/Application Support/REAPER/" CACHE STRING "Extension path prefix, prepended onto extension install directory")
    endif()
    if(WIN32)
        set(EPS_PLUGIN_INSTALL_PREFIX "${PROG_FILES}/Common Files/VST3/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
        set(EPS_EXTENSION_INSTALL_PREFIX "${APPDATA}/REAPER/" CACHE STRING "Extension path prefix, prepended onto extension install directory")
    endif()
    if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
        set(EPS_PLUGIN_INSTALL_PREFIX "$ENV{HOME}/.vst3/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
        set(EPS_EXTENSION_INSTALL_PREFIX "$ENV{HOME}/.config/REAPER/" CACHE STRING "Extension path prefix, prepended onto extension install directory")
    endif()
else()
    set(EPS_PLUGIN_INSTALL_PREFIX "VST3/" CACHE STRING "Plugin path prefix, prepended onto plugin install directories")
    set(EPS_EXTENSION_INSTALL_PREFIX "" CACHE STRING "Extension path prefix, prepended onto extension install directory")
endif()
endfunction()
