#pragma once
#include <string>

namespace eps {

enum class TextID {
  EXTENSION_ERROR_TITLE,
  CONTEXT_MENU,
  EXPLODE_ACTION_PREFIX,
  EXPLODE_ERROR_TITLE,
  EXPLODE_ERROR_DESCRIPTION,
  CREATE_PROJECT_ACTION_PREFIX,
  CREATE_PROJECT_MENU,
  CREATE_PROJECT_FILE_PROMPT,
  CREATE_PROJECT_ERROR_TITLE,
  CREATE_PROJECT_ERROR_DESCRIPTION,
  IMPORT_MENU,
  IMPORT_ACTION_PREFIX,
  IMPORT_FILE_PROMPT,
  IMPORT_ERROR_TITLE,
  IMPORT_ERROR_DESCRIPTION
};

std::string uiText(TextID item);
}
