#pragma once
#include <string>

namespace eps {

enum class TextID {
  EXTENSION_ERROR_TITLE,
  CONTEXT_MENU,
  EXPLODE_ACTION_PREFIX,
  EXPLODE_ERROR_TITLE,
  EXPLODE_ERROR_DESCRIPTION,
  CREATE_PROJECT_ACTION_PREFIX,
  CREATE_PROJECT_MENU,
  CREATE_PROJECT_FILE_PROMPT,
  CREATE_PROJECT_ERROR_TITLE,
  CREATE_PROJECT_ERROR_DESCRIPTION,
  IMPORT_MENU,
  IMPORT_ACTION_PREFIX,
  IMPORT_FILE_PROMPT,
  IMPORT_ERROR_TITLE,
  IMPORT_ERROR_DESCRIPTION,
  RENDERER_VALIDATING_DIALOG,
  RENDERER_EXPORT_SOURCE_PREFIX,
  RENDERER_ERROR_NO_EXPORT_SOURCES,
  RENDER_LOG_ERROR_HEADER,
  RENDER_LOG_WARNING_HEADER,
  RENDER_LOG_INFO_HEADER,
  RENDERER_ERROR_FAILED_CONTROL_OVERRIDE,
  EXPORT_DIALOG_TAKEOVER_TEXT_FOR_CHANNEL_COUNT,
  EXPORT_DIALOG_FALLBACK_VALUE_FOR_CHANNEL_COUNT,
  EXPORT_HANDLER_ERROR_NO_VALID_SOURCES,
  EXPORT_HANDLER_ERROR_NO_CHANNELS,
  EXPORT_HANDLER_WARNING_MULTIPLE_SOURCE_TYPES,
  EXPORT_SINK_ERROR_NO_SOURCES,
  EXPORT_SINK_ERROR_NO_SOURCES_TITLE,
  EXPORT_SINK_ERROR_NO_CHANNELS,
  EXPORT_SINK_ERROR_NO_CHANNELS_TITLE,
  EXPORT_SINK_ERROR_SAMPLE_RATE,
  EXPORT_SINK_ERROR_SAMPLE_RATE_TITLE,
  EXPORT_SINK_ISSUES_HEADER,
  EXPORT_SINK_ISSUES_TITLE,
  EXPORT_SINK_ERROR_NO_ADM,
  EXPORT_SINK_ERROR_NO_ADM_TITLE,
  EXPORT_SINK_WARNING_FRAMES,
  EXPORT_SINK_WARNING_FRAMES_TITLE,
  EXPORT_SINK_INFO_RENDERING,
  EXPORT_SINK_WARNING_BAD_STRUCTURE
};

std::string uiText(TextID item);
}
