submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/reaperapi.h" ReaperAPI > "test/reaper_adm/mocks/reaperapi.h"
submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pluginsuite.h" PluginSuite > "test/reaper_adm/mocks/pluginsuite.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/channelindexer.h" IChannelIndexer > "test/reaper_adm/mocks/channelindexer.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/node.h" INode MediaTakeNode MediaTrackNode > "test/reaper_adm/mocks/node_tmp.h"
# #submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmgroup.h" IPCMGroup > "test/reaper_adm/mocks/pcmgroup.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmgroupfile.h" IPCMGroupFile > "test/reaper_adm/mocks/pcmgroupfile.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmreader.h" IPCMBlock PCMReader > "test/reaper_adm/mocks/pcmreader.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmwriter.h" IPCMWriter > "test/reaper_adm/mocks/pcmwriter.h"
submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmsourcecreator.h" IPCMSourceCreator > "test/reaper_adm/mocks/pcmsourcecreator.h"
submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/nodefactory.h" NodeFactory > "test/reaper_adm/mocks/nodefactory.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/admmetadata.h" IADMMetaData > "test/reaper_adm/mocks/admmetadata.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmwriterfactory.h" PCMWriterFactory > "test/reaper_adm/mocks/pcmwriterfactory.h"
# submodules/googletest/googlemock/scripts/generator/gmock_gen.py "src/reaper_adm/pcmgroupregistry.h" IPCMGroupRegistry > "test/reaper_adm/mocks/pcmgroupregistry.h"
