# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EAR Production Suite
email: ear-production-suite-admins@list.ebu.ch
description: > # this means to ignore newlines until "baseurl:"
  The EAR Production Suite enables you to produce ADM content natively without
  being tied to a specific NGA codec. It is a joint development of BBC R&D and
  IRT as an EBU project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ear-production-suite.ebu.io/" # the base hostname & protocol for your site

# Social
githubUsername:
twitterUsername:
dribbbleUsername:
codepenUsername:

# Build settings
markdown: CommonMarkGhPages

themeColor: dark # green, blue, orange, purple, grey
fixedNav: 'false' # true or false


permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
